id: P003062
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016678
  title: ལྷོ་ལུང་དཀར་དགོན་གྱི་གདན་རབས་ཆོས་འབྱུང
  author: ''
  volumes:
    f583e8ba09954ef19cf3c44dfabc2ca5:
      image_group_id: I01JW58
      title: ''
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
