id: IC4377072
legacy_id: P003062
ocr_import_info:
  bdrc_scan_id: W00EGS1016678
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T01:25:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:43:09.841415+00:00'
last_modified: 2022-08-30 22:43:40.398184
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016678
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016678
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷོ་ལུང་དཀར་དགོན་གྱི་གདན་རབས་ཆོས་འབྱུང་།
  author: འབྲོང་སྤྲུལ ༠༧་དཀོན་མཆོག་ལྷུན་གྲུབ་སྙན་གྲགས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9078780533255066
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I01JW58:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW58
      total_pages: 542
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW58.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9078780533255066
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
